"""
Django settings for nmrcen project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')9^)1yl#w#)4_o+nsy5s&0tp&(yn@l_t37t=ovwhf^n6m-i4*2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "nmrcen.xmu.edu.cn"]
ADMINS = [('nmrcen', 'nmrcen@163.com'),]

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'schedule',
    'homepages',
    'accounts',
    'eguard',
    'blogs',
    'taggit',
    'weixin',
    'password_reset',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

#AUTHENTICATION_BACKENDS = (
#    'django.contrib.auth.backends.ModelBackend', 
#)

ROOT_URLCONF = 'nmrcen.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'nmrcen.context_processors.google_analytics',
            ],
        },
    },
]

WSGI_APPLICATION = 'nmrcen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join( BASE_DIR, "static" ),
]
#STATIC_ROOT = os.path.join( BASE_DIR, "static" )

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join( BASE_DIR, 'media' )

AUTH_USER_MODEL = 'accounts.CustomUser'

GOOGLE_ANALYTICS_PROPERTY_ID = 'UA-68383122-1'
GOOGLE_ANALYTICS_DOMAIN = 'nmrcen.xmu.edu.cn'

# email settings
with open(os.path.join( BASE_DIR, "secretkeys.txt")) as f:
    settings = dict([line.strip().split() for line in f.readlines()])
SERVER_EMAIL = settings["server_email"]
EMAIL_HOST = settings["email_host"]
EMAIL_HOST_USER = settings["email_host_user"]
EMAIL_HOST_PASSWORD = settings["email_host_password"]
DEFAULT_FROM_EMAIL = settings["default_from_email"]
EMAIL_POST = settings["email_post"]
EMAIL_USE_TLS = True
