# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='md5',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
