# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 08:06
from __future__ import unicode_literals

import blogs.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('md_file', models.FileField(blank=True, upload_to=blogs.models.get_upload_md_name)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name=b'date published')),
                ('last_edit_date', models.DateTimeField(auto_now=True, verbose_name=b'last edited')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('html_file', models.FileField(blank=True, upload_to=blogs.models.get_html_name)),
                ('category', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blogs.models.get_upload_img_name)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogs.BlogPost')),
            ],
        ),
    ]
