# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[(b'nmr', b'NMR'), (b'lx', b'Linux/Ubuntu'), (b'pl', b'Personal'), (b'pg', b'Python/Programming'), (b'ot', b'Others')], max_length=30),
        ),
    ]
