# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 07:16
from __future__ import unicode_literals

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20160304_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=blogs.models.get_upload_img_name),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('nmr', b'NMR'), ('lx', b'Linux/Ubuntu'), ('news', b'News'), ('pr', b'Project'), ('pl', b'Personal'), ('pg', b'Python/Programming'), ('ot', b'Others')], max_length=30),
        ),
    ]
