# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20160307_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('nmr', 'NMR'), ('lx', 'Linux/Ubuntu'), ('news', 'News'), ('pr', 'Projects'), ('hot', 'Hot Spot'), ('pl', 'Personal'), ('pg', 'Python/Programming'), ('ot', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last edited'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
