# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20161006_1654'),
        ('blogs', '0006_auto_20160312_1051'),
    ]

    operations = [
    ]
