# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_merge_20161006_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='md5',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
