# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_operate_500MHz', 'Can operate 500MHz'), ('can_operate_600MHz', 'Can operate 600MHz'), ('can_operate_850MHz', 'Can operate 850MHz'), ('operate_MS', 'Can operate MS'))},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2116, 1, 27, 17, 53, 4, 869667), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='\u7f51\u7ad9\u7ba1\u7406\u8005'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=b'/static/images/defaultuserimage.png', upload_to=b'uploads', verbose_name='\u4e2a\u4eba\u7167\u7247'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_bio',
            field=models.TextField(blank=True, max_length=600, verbose_name='\u81ea\u6211\u4ecb\u7ecd'),
        ),
    ]
