# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160220_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_sample_500MHz', '\u9001\u6837500MHz'), ('can_operate_500MHz', '\u64cd\u4f5c500MHz'), ('can_sample_600MHz', '\u9001\u6837600MHz'), ('can_operate_600MHz', '\u64cd\u4f5c600MHz'), ('can_sample_850MHz', '\u9001\u6837850MHz'), ('can_operate_850MHz', '\u64cd\u4f5c850MHz'), ('can_sample_LCMS', '\u9001\u6837LCMS'), ('can_operate_LCMS', '\u64cd\u4f5cLCMS'))},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2116, 1, 27, 21, 51, 29, 709956), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
    ]
