# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 02:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160220_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 1, 28, 10, 19, 18, 833303), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
    ]
