# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160222_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=b'unkown@xmu.edu.cn', help_text='\u6709\u6548\u90ae\u7bb1\uff0c\u7528\u4e8e\u8ba4\u8bc1\u901a\u77e5', max_length=255, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 1, 29, 20, 40, 35, 621265), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identify',
            field=models.CharField(help_text='\u53a6\u5927\u5b66\u751f\u53f7\u6216\u8005\u6559\u5de5\u53f7\uff0c\u975e\u53a6\u5927\u5b66\u751f\u6216\u8005\u6559\u5e08\u4e0d\u7528\u586b', max_length=30, null=True, unique=True, verbose_name='\u5b66\u53f7/\u6559\u5de5\u53f7'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='person_in_charge',
            field=models.ForeignKey(help_text='\u8bfe\u9898\u7ec4\u8d1f\u8d23\u4eba, \u5bfc\u5e08\u6216\u8005\u9886\u5bfc', on_delete=django.db.models.deletion.CASCADE, to='accounts.PersonInCharge', verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=b'05920000000', help_text='\u683c\u5f0f\u4e3a05922186874\u6216\u8005\u624b\u673a\u53f7\u7801', max_length=18, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='personincharge',
            name='email',
            field=models.EmailField(default=b'unkown@xmu.edu.cn', help_text='\u6709\u6548\u90ae\u7bb1\uff0c\u7528\u4e8e\u8ba4\u8bc1\u901a\u77e5', max_length=255, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='personincharge',
            name='phone_number',
            field=models.CharField(default=b'05920000000', help_text='\u683c\u5f0f\u4e3a05922186874\u6216\u8005\u624b\u673a\u53f7\u7801', max_length=18, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='personincharge',
            name='surname',
            field=models.CharField(help_text='\u7528\u6237\u7684\u771f\u5b9e\u59d3\u540d', max_length=30, unique=True, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='personincharge',
            name='titles',
            field=models.CharField(choices=[(b'PI', '\u8bfe\u9898\u7ec4\u8d1f\u8d23\u4eba'), (b'FL', '\u7ecf\u8d39\u8d1f\u8d23\u4eba'), (b'OL', '\u516c\u53f8\u9886\u5bfc')], default=b'PI', max_length=3, verbose_name='\u804c\u52a1'),
        ),
    ]
