# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 07:43
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160222_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 1, 30, 15, 43, 3, 707585), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identify',
            field=models.CharField(blank=True, help_text='\u53a6\u5927\u5b66\u751f\u53f7\u6216\u8005\u6559\u5de5\u53f7\uff0c\u975e\u53a6\u5927\u5b66\u751f\u6216\u8005\u6559\u5e08\u4e0d\u7528\u586b', max_length=30, null=True, unique=True, verbose_name='\u5b66\u53f7/\u6559\u5de5\u53f7'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='\u6d3b\u8dc3'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=b'/media/profile/default.png', upload_to=b'profile', verbose_name='\u4e2a\u4eba\u7167\u7247'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='\u7eaf\u6570\u5b57\u548c\u5b57\u6bcd', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', message='\u53ea\u6709[0-9a-z-A-Z]\u5b57\u7b26\u53ef\u4ee5.')], verbose_name='\u7528\u6237\u540d'),
        ),
    ]
