# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 02:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160224_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 2, 1, 10, 1, 55, 21678), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='personincharge',
            name='orgnization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Orgnization', verbose_name='\u5355\u4f4d'),
        ),
    ]
