# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160225_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 2, 1, 14, 40, 5, 572257), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='person_in_charge',
            field=models.ForeignKey(blank=True, help_text='\u8bfe\u9898\u7ec4\u8d1f\u8d23\u4eba, \u5bfc\u5e08\u6216\u8005\u9886\u5bfc', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.PersonInCharge', verbose_name='\u8d1f\u8d23\u4eba'),
        ),
    ]
