# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 12:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160225_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 2, 3, 20, 16, 46, 318925), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
    ]
