# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20160312_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateField(default=datetime.date(2116, 9, 12), verbose_name='失效日期'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='person_in_charge',
            field=models.ForeignKey(blank=True, help_text='课题组负责人, 导师或者领导，里面找不到暂时不用填写，登录以后请修改个人资料！', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.PersonInCharge', verbose_name='负责人'),
        ),
    ]
