# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 10:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20161006_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateField(default=datetime.date(2116, 9, 18), verbose_name='失效日期'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile/default.png', upload_to='profile', verbose_name='个人照片'),
        ),
    ]
