# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 07:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20161012_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='个人网页'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expired_time',
            field=models.DateField(default=datetime.date(2116, 10, 16), verbose_name='失效日期'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('student', '厦大学生'), ('staff', '厦大教师'), ('temp', '临时卡'), ('visit', '其他')], default='student', max_length=7, verbose_name='身份'),
        ),
    ]
