# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('instrument', models.CharField(choices=[(b'500MHz', b'500MHz NMR'), (b'600MHz', b'600MHz NMR'), (b'850MHz', b'850MHz NMR'), (b'MS', b'QTop MS')], default=b'600Mhz', max_length=6)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_operate_500MHz', 'Can operate 500MHz'), ('can_operate_600MHz', 'Can operate 600MHz'), ('can_operate_850MHz', 'Can operate 850MHz'), ('operate_MS', 'Can operate MS')),
            },
        ),
    ]
