# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('solvent', models.CharField(blank=True, max_length=30, null=True)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('structure', models.CharField(blank=True, max_length=1000, null=True)),
                ('others', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='remark',
            new_name='measure_type',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='stop_time',
        ),
        migrations.AddField(
            model_name='experiment',
            name='times',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='sample',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.Sample'),
        ),
    ]
