# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('introduct', models.TextField(blank=True, null=True, verbose_name='\u4ecb\u7ecd')),
                ('image', models.ImageField(default=b'/media/images/default.png', upload_to=b'images', verbose_name='\u7167\u7247')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='\u6388\u6743\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_datetime', models.DateTimeField(blank=True, help_text='\u8bf7\u9009\u62e9\u4e00\u4e2a\u9884\u5b9a\u65f6\u95f4\uff0c\u7b49\u5f85\u7ba1\u7406\u5458\u786e\u5b9a\uff01', null=True, verbose_name='\u9884\u5b9a\u65e5\u671f')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('has_approved', models.NullBooleanField(help_text='\u7a7a\u7740\u8868\u793a\u672a\u5904\u7406', verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\xb5\x9e\xe5\x90\x8c')),
                ('feedback', models.TextField(blank=True, max_length=300, null=True, verbose_name='\u53cd\u9988\u4fe1\u606f')),
                ('instrument', models.ManyToManyField(to='schedule.Instrument', verbose_name='\u4eea\u5668')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7533\u8bf7\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('solvent', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6c18\u4ee3\u8bd5\u5242')),
                ('concentration', models.FloatField(blank=True, null=True, verbose_name='\u6d53\u5ea6/ML')),
                ('molecular_weight', models.FloatField(blank=True, null=True, verbose_name='\u5206\u5b50\u91cf')),
                ('structure', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u5316\u5b66\u5f0f')),
                ('others', models.TextField(blank=True, null=True, verbose_name='\u5176\u4ed6')),
            ],
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={},
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='stop_time',
        ),
        migrations.AddField(
            model_name='experiment',
            name='measure_type',
            field=models.TextField(blank=True, help_text='\u5b9e\u9a8c\u6d4b\u91cf\u7c7b\u578b\uff0cC13\uff0cH1\uff0c HSQC\uff0cHMBC\u7b49', null=True, verbose_name='\u5b9e\u9a8c\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='times',
            field=models.IntegerField(default=0, help_text='\u5b9e\u9a8c\u9884\u4f30\u7528\u65f6\uff0c\u8bf7\u53c2\u8003\u4e0d\u540c\u5b9e\u9a8c\u4f30\u8ba1\u7528\u65f6\uff01', verbose_name='\u5b9e\u9a8c\u7528\u65f6/\u5c0f\u65f6'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Instrument', verbose_name='\u4eea\u5668\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='start_time',
            field=models.DateTimeField(help_text='\u5b9e\u9a8c\u9884\u7ea6\u8d77\u59cb\u65f6\u95f4', verbose_name='\u8d77\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Sample', verbose_name='\u6837\u54c1\u53c2\u6570'),
        ),
    ]
