# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160219_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='measure_type',
            field=models.TextField(blank=True, help_text='jjjjjjj', null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Sample'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='times',
            field=models.IntegerField(help_text='how many hours', verbose_name='Time/hours'),
        ),
    ]
