# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20160220_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='instrument',
            field=models.CharField(choices=[(b'500MHz', b'500MHz NMR'), (b'600MHz', b'600MHz NMR'), (b'850MHz', b'850MHz NMR'), (b'MS', b'QTop MS')], default=b'600Mhz', max_length=6, verbose_name='\u4eea\u5668\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='measure_type',
            field=models.TextField(blank=True, help_text='\u5b9e\u9a8c\u6d4b\u91cf\u7c7b\u578b\uff0cC13\uff0cH1\uff0c HSQC\uff0cHMBC\u7b49', null=True, verbose_name='\u5b9e\u9a8c\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Sample', verbose_name='\u6837\u54c1\u53c2\u6570'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='start_time',
            field=models.DateTimeField(help_text='\u5b9e\u9a8c\u9884\u7ea6\u8d77\u59cb\u65f6\u95f4', verbose_name='\u8d77\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='times',
            field=models.IntegerField(help_text='\u5b9e\u9a8c\u9884\u4f30\u7528\u65f6\uff0c\u8bf7\u53c2\u8003\u4e0d\u540c\u5b9e\u9a8c\u4f30\u8ba1\u7528\u65f6\uff01', verbose_name='\u5b9e\u9a8c\u7528\u65f6/\u5c0f\u65f6'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
