# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20160220_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={},
        ),
    ]
