# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0006_auto_20160220_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('introduct', models.TextField(blank=True, null=True, verbose_name='\u4ecb\u7ecd')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='\u6388\u6743\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_datetime', models.DateTimeField(blank=True, help_text='\u8bf7\u9009\u62e9\u4e00\u4e2a\u9884\u5b9a\u65f6\u95f4\uff0c\u7b49\u5f85\u7ba1\u7406\u5458\u786e\u5b9a\uff01', null=True, verbose_name='\u9884\u5b9a\u65e5\u671f')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ManyToManyField(to='schedule.Instrument', verbose_name='\u4eea\u5668')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7533\u8bf7\u4eba')),
            ],
        ),
    ]
