# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_instrument_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentappointment',
            name='has_approved',
            field=models.NullBooleanField(help_text='\u7a7a\u7740\u8868\u793a\u672a\u5904\u7406', verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\xb5\x9e\xe5\x90\x8c'),
        ),
    ]
