# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160227_2008'),
        ('schedule', '0010_instrumentappointment_feedback'),
    ]

    operations = [
    ]
