# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Instrument', verbose_name='\u9009\u62e9\u4eea\u5668'),
        ),
    ]
