# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_instrument_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='short_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u7b80\u79f0'),
        ),
    ]
