# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20160228_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='times',
            field=models.FloatField(help_text='\u5b9e\u9a8c\u9884\u4f30\u7528\u65f6\uff0c\u8bf7\u53c2\u8003\u4e0d\u540c\u5b9e\u9a8c\u4f30\u8ba1\u7528\u65f6\uff01', verbose_name='\u5b9e\u9a8c\u7528\u65f6/\u5c0f\u65f6'),
        ),
    ]
