# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0015_auto_20160301_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='\u5b9e\u9a8c\u9884\u7ea6\u8d77\u59cb\u65f6\u95f4', verbose_name='\u8d77\u59cb\u65f6\u95f4')),
                ('times', models.FloatField(help_text='\u5b9e\u9a8c\u9884\u4f30\u7528\u65f6\uff0c\u8bf7\u53c2\u8003\u4e0d\u540c\u5b9e\u9a8c\u4f30\u8ba1\u7528\u65f6\uff01', verbose_name='\u5b9e\u9a8c\u7528\u65f6/\u5c0f\u65f6')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('has_approved', models.NullBooleanField(help_text='\u7a7a\u7740\u8868\u793a\u672a\u5904\u7406', verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\xb5\x9e\xe5\x90\x8c')),
                ('feedback', models.TextField(blank=True, max_length=300, null=True, verbose_name='\u53cd\u9988\u4fe1\u606f')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Instrument', verbose_name='\u9009\u62e9\u4eea\u5668')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Sample', verbose_name='\u6837\u54c1\u53c2\u6570')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='sample',
        ),
    ]
