# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20160302_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='upload',
            field=models.FileField(default='/media/samples/default.txt', upload_to=b'samples/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(default=b'2016030219', max_length=100, verbose_name='\u540d\u79f0'),
        ),
    ]
