# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20160302_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='concentration',
            field=models.FloatField(blank=True, null=True, verbose_name='\u6d53\u5ea6/mM'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(default=b'2016030214', max_length=100, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=b'samples/'),
        ),
    ]
