# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_auto_20160302_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentappointment',
            name='times',
            field=models.FloatField(default=0.5, help_text='\u9884\u4f30\u57f9\u8bad\u4f7f\u7528\u65f6\u95f4', verbose_name='\u7528\u65f6/\u5c0f\u65f6'),
        ),
        migrations.AlterField(
            model_name='instrumentappointment',
            name='instrument',
            field=models.ManyToManyField(help_text='\u901a\u8fc7\u6309\u4f4fCtrl\u6765\u5b9e\u73b0\u591a\u9009\uff01', to='schedule.Instrument', verbose_name='\u4eea\u5668'),
        ),
    ]
