# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20160311_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(default='/media/images/default.png', upload_to='images', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='instrumentappointment',
            name='has_approved',
            field=models.NullBooleanField(help_text='空着表示未处理', verbose_name='是否赞同'),
        ),
        migrations.AlterField(
            model_name='instrumentappointment',
            name='times',
            field=models.FloatField(default=0.5, help_text='预估培训使用时间,如果不需要培训把这个数值设置为0.', verbose_name='用时/小时'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='samples/'),
        ),
        migrations.AlterField(
            model_name='sampleappointment',
            name='has_approved',
            field=models.NullBooleanField(help_text='空着表示未处理', verbose_name='是否赞同'),
        ),
    ]
