# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_auto_20160312_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleappointment',
            name='measure_type',
            field=models.TextField(blank=True, help_text='实验测量类型，C13，H1， HSQC，HMBC等, 以及谱宽等实验参数特殊说明。默认sw（1H）=20ppm，o1p（1H）=6.2ppm，sw（13C）=240ppm，o1p（13C）=100ppm。', null=True, verbose_name='实验类型'),
        ),
    ]
