# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 09:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('webId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(default='\u5316\u5b66\u5316\u5de5\u5b66\u9662', max_length=100)),
                ('orgnization', models.CharField(default='\u53a6\u95e8\u5927\u5b66', max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('introduction', models.TextField()),
                ('linker', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[(b'M', b'Men'), (b'G', b'Girl'), (b'-', b'Unkown')], default=b'-', max_length=1)),
                ('identify', models.CharField(max_length=30, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message=b'phone number must bo entered in format: +86100000000 or 100000000, up to 15 digits allowed!', regex=b'^\\+?1?\\d{6,15}')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('signedDatetime', models.DateTimeField(auto_now_add=True)),
                ('expiredDatetime', models.DateTimeField(blank=True, null=True)),
                ('isPI', models.BooleanField(default=False)),
                ('isStaff', models.BooleanField(default=False)),
                ('entrance', models.ManyToManyField(blank=True, to='eguard.Entrance')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eguard.Team')),
            ],
            options={
                'ordering': ('group',),
            },
        ),
    ]
