# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 02:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eguard', '0003_auto_20160220_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u7533\u8bf7\u7406\u7531')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('expired_time', models.DateField(default=datetime.datetime(2116, 1, 28, 10, 18, 46, 94241), verbose_name='\u5931\u6548\u65e5\u671f')),
            ],
        ),
        migrations.RemoveField(
            model_name='entrance',
            name='users',
        ),
        migrations.AddField(
            model_name='entranceappointment',
            name='entrance',
            field=models.ManyToManyField(to='eguard.Entrance', verbose_name='\u95e8\u7981'),
        ),
        migrations.AddField(
            model_name='entranceappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u51fa\u5165\u8005'),
        ),
    ]
