# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eguard', '0004_auto_20160221_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='name',
            field=models.CharField(default='\u503c\u73ed\u5ba4\u5927\u95e8', max_length=100, verbose_name='\u95e8\u7981'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='code',
            field=models.CharField(default=b'D102', max_length=4, verbose_name='\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 1, 28, 10, 37, 10, 676529), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='reason',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='\u7533\u8bf7\u7406\u7531'),
        ),
    ]
