# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 00:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eguard', '0005_auto_20160221_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6388\u6743\u8005'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 1, 29, 8, 41, 25, 160231), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7533\u8bf7\u4eba'),
        ),
        migrations.AlterField(
            model_name='event',
            name='entrance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eguard.Entrance', verbose_name='\u95e8\u53f7'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u51fa\u5165\u8005'),
        ),
    ]
