# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 00:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eguard', '0006_auto_20160222_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrance',
            name='user',
        ),
        migrations.AddField(
            model_name='entrance',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='\u6388\u6743\u8005'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 1, 29, 8, 43, 12, 490481), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
    ]
