# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 08:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eguard', '0007_auto_20160222_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceappointment',
            name='has_approved',
            field=models.NullBooleanField(help_text='\u7a7a\u7740\u8868\u793a\u672a\u5904\u7406', verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\xb5\x9e\xe5\x90\x8c'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='\u6388\u6743\u8005'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 2, 3, 16, 6, 50, 151403), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
    ]
