# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eguard', '0008_auto_20160227_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceappointment',
            name='feedback',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='\u53cd\u9988\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 2, 3, 16, 10, 40, 745355), verbose_name='\u5931\u6548\u65e5\u671f'),
        ),
    ]
