# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eguard', '0009_auto_20160227_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='code',
            field=models.CharField(default='D102', max_length=4, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='entrance',
            field=models.ManyToManyField(help_text='进出核磁中心请同时申请“值班室大门”，“值班室里门”；而其他申请请根据需求来。通过按住Ctrl来实现多选！', to='eguard.Entrance', verbose_name='门禁'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='expired_time',
            field=models.DateField(default=datetime.datetime(2116, 2, 17, 10, 51, 42, 188074), verbose_name='失效日期'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='has_approved',
            field=models.NullBooleanField(help_text='空着表示未处理', verbose_name='是否赞同'),
        ),
        migrations.AlterField(
            model_name='entranceappointment',
            name='reason',
            field=models.TextField(blank=True, help_text='请给出申请理由，不然可能会导致申请不通过！', max_length=300, null=True, verbose_name='申请理由'),
        ),
    ]
